spring:
  application:
    name: easylinker-admin
  zipkin:
    base-url: http://localhost:2530

server:
  port: 2520

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:2510/eureka/

management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: health,info