spring:
  application:
    name: easylinker-zuul
  boot:
    admin:
      client:
        url: http://localhost:2520
  zipkin:
    base-url: http://localhost:2530

server:
  port: 2550

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:2510/eureka/

management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: health,info